export const categoriesData = [
  {
    icon: "/assets/imgs/home/musicians.png",
    label: "General",
    to: "/general",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/keys.png",
    label: "Keys/Paino",
    to: "/keys",
    types: [
      {label:"Synth's", icon: "/assets/imgs/home/keys.png"},
      {label:"MIDI", icon: "/assets/imgs/home/keys.png"},
      {label:"Beat Production", icon: "/assets/imgs/home/keys.png"},
      {label:"Electric Piano's", icon: "/assets/imgs/home/keys.png"},
      {label:"Acoustic Piano's", icon: "/assets/imgs/home/keys.png"},
      {label:"Keys Accessorie's", icon: "/assets/imgs/home/keys.png"},
      {label:"Organ's", icon: "/assets/imgs/home/keys.png"},
      {label:"Workstation's", icon: "/assets/imgs/home/keys.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/drums.png",
    label: "Drums",
    to: "/drums",
    types: [
      {label:"Acoustic Drum's", icon: "/assets/imgs/home/drums.png"},
      {label:"Cymbal's", icon: "/assets/imgs/home/drums.png"},
      {label:"Aux Percussion", icon: "/assets/imgs/home/drums.png"},
      {label:"Electric Drum's", icon: "/assets/imgs/home/drums.png"},
      {label:"Drum Accessorie's", icon: "/assets/imgs/home/drums.png"},
      {label:"Drum Part's", icon: "/assets/imgs/home/drums.png"},
      {label:"Other Drum's", icon: "/assets/imgs/home/drums.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/guitar.png",
    label: "Guitar",
    to: "/guitar",
    types: [
      {label:"Electric Guitar", icon: "/assets/imgs/home/guitar.png"},
      {label:"Acoustic Guitar", icon: "/assets/imgs/home/guitar.png"},
      {label:"Guitar Part's", icon: "/assets/imgs/home/guitar.png"},
      {label:"Guitars Accessorie's", icon: "/assets/imgs/home/guitar.png"},
      {label:"Left-Handed", icon: "/assets/imgs/home/guitar.png"},
      {label:"6-Strings+", icon: "/assets/imgs/home/guitar.png"},
      {label:"Folk Instrument's", icon: "/assets/imgs/home/guitar.png"},
      {label:"Vintage Guitar's", icon: "/assets/imgs/home/guitar.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/bass.png",
    label: "Bass",
    to: "/bass",
    types: [
      {label:"4-String's", icon: "/assets/imgs/home/bass.png"},
      {label:"5-String's+", icon: "/assets/imgs/home/bass.png"},
      {label:"Short Scale", icon: "/assets/imgs/home/bass.png"},
      {label:"Left-Handed", icon: "/assets/imgs/home/bass.png"},
      {label:"Fretless", icon: "/assets/imgs/home/bass.png"},
      {label:"Acoustic Bass", icon: "/assets/imgs/home/bass.png"},
      {label:"Vintage Bass", icon: "/assets/imgs/home/bass.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/pedalamps.png",
    label: "Pedals",
    to: "/pedals",
    types: [
      {label:"Overdrive/Boost",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Fuzz",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Delay",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Reverb",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Multi-Effects",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Distortion",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Loop/Sampler",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Chorus/Vibrato",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Compressor/Sustain",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Octave/Pitch",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Tremolo/Flanger",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Wahs/Filter/Phase",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"EQ/Tuner",icon: "/assets/imgs/home/pedalamps.png"},
      {label:"Pedal Accessories",icon: "/assets/imgs/home/pedalamps.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/gigs.png",
    label: "Gigging",
    to: "/gigging",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/live.png",
    label: "Live Sound",
    to: "/live",
    types: [
      {label:"PA Systems/Speakers", icon: "/assets/imgs/home/live.png"},
      {label:"DI", icon: "/assets/imgs/home/live.png"},
      {label:"Live Mixer", icon: "/assets/imgs/home/live.png"},
      {label:"Microphones", icon: "/assets/imgs/home/live.png"},
      {label:"Lighting", icon: "/assets/imgs/home/live.png"},
      {label:"Live Accessories", icon: "/assets/imgs/home/live.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/recording.png",
    label: "Recording",
    to: "/rec",
    types: [
      {label:"Recording Equipment", icon: "/assets/imgs/home/recording.png"},
      {label:"Audio Interface", icon: "/assets/imgs/home/recording.png"},
      {label:"Mixer", icon: "/assets/imgs/home/recording.png"},
      {label:"Microphones", icon: "/assets/imgs/home/recording.png"},
      {label:"Headphones", icon: "/assets/imgs/home/recording.png"},
      {label:"Studio Monitors", icon: "/assets/imgs/home/recording.png"},
      {label:"Pre-amps/Channel Strips", icon: "/assets/imgs/home/recording.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/prod.png",
    label: "Producers",
    to: "/prod",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/dj.png",
    label: "DJ/Audio",
    to: "/dj",
    types: [
      {label:"PA Speakers", icon: "/assets/imgs/home/dj.png"},
      {label:"Portable Speakers", icon: "/assets/imgs/home/dj.png"},
      {label:"DJ Controllers", icon: "/assets/imgs/home/dj.png"},
      {label:"Mixer ", icon: "/assets/imgs/home/dj.png"},
      {label:"Turntables", icon: "/assets/imgs/home/dj.png"},
      {label:"DJ Accessories", icon: "/assets/imgs/home/dj.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/amplifier.png",
    label: "Amps",
    to: "/amps",
    types: [
      {label:"Guitar Combos", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Guitar Heads", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Guitar Cabinets", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Bass Combos ", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Bass Heads", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Bass Cabinets", icon: "/assets/imgs/home/amplifier.png"},
      {label:"Keys Amp", icon: "/assets/imgs/home/amplifier.png"},
    ],
  },
  {
    icon: "/assets/imgs/home/vintage.png",
    label: "Vintage",
    to: "/vintage",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/mixing.png",
    label: "Mixing",
    to: "/mixing",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/workers.png",
    label: "Luthiers",
    to: "/luthiers",
    types: [{label:"None"}],
  },
  {
    icon: "/assets/imgs/home/wind.png",
    label: "Wind",
    to: "/wind",
    types: [
      {label:"Saxophones", icon: "/assets/imgs/home/wind.png"},
      {label:"Flutes", icon: "/assets/imgs/home/wind.png"},
      {label:"Woodwind", icon: "/assets/imgs/home/wind.png"},
      {label:"Brass", icon: "/assets/imgs/home/wind.png"},
      {label:"Trumpets", icon: "/assets/imgs/home/wind.png"},
      {label:"Trombones", icon: "/assets/imgs/home/wind.png"},
    ],
  },
];


export const soloCategoriesData = [
  "General",
  "Drums",
  "Guitars",
  "Bass",
  "Keys/Paino",
  "Pedals",
  "Amps",
  "Live Sound",
  "Studio",
  "Vintage/Rare",
  "DJ/Audio Gear",
  "Producers",
  "Luthiers",
  "Wind",
  "Mixing",
  "Recording Gear",
];
export const soloSubCategoriesData = ["Setup", "Learning", "Content", "Live", "Setup", "GearTalk", "Luthiers", "More"];
export const subCategoriesData = [
  { label: "Gigging", icon: "/assets/vectors/navbar/music.svg" },
  { label: "Live", icon: "/assets/vectors/navbar/music.svg" },
  { label: "Learning", icon: "/assets/vectors/navbar/music.svg" },
  { label: "Setup", icon: "/assets/vectors/navbar/music.svg" },
  { label: "GearTalk", icon: "/assets/vectors/navbar/music.svg" },
  { label: "Fun", icon: "/assets/vectors/navbar/music.svg" },
  { label: "Luthiers", icon: "/assets/vectors/navbar/music.svg" },
  { label: "More", icon: "/assets/vectors/navbar/music.svg" },
];